name: pchome-crawler

on:
  schedule:
    - cron: "0 2 * * *"   # 每天台北 10:00（UTC+8）
  workflow_dispatch: {}

concurrency:
  group: pchome-crawler
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          MPLBACKEND: Agg
        run: |
          mkdir -p data charts
          python crawler.py
          echo "==== After crawler ===="
          ls -al data || true
          ls -al charts || true

      - name: Upload artifacts (data & charts)
        uses: actions/upload-artifact@v4
        with:
          name: pchome-output
          path: |
            data/
            charts/

      - name: Commit results (robust)
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config core.quotepath false   # 讓中文檔名在 log 裡顯示而不是亂碼

          git add -A
          git status

          CHANGES=$(git diff --cached --name-only | wc -l | tr -d ' ')
          echo "Staged changes: $CHANGES"

          if [ "$CHANGES" -gt 0 ]; then
            MSG="data: update PChome keywords on $(TZ=Asia/Taipei date +'%Y-%m-%d %H:%M')"
            git commit -m "$MSG"

            # 關鍵：先把遠端 main 的新提交 rebase 進來，再 push
            git fetch origin
            if ! git pull --rebase origin main; then
              echo "Rebase failed, fallback to a merge (ours wins)."
              git rebase --abort || true
              git merge -X ours --no-edit origin/main || true
            fi

            git push
          else
            echo "No changes to commit."
          fi
